# Site settings
title: Маняня
email: pochta@manyanya03.ru
description: Клуб детей, родителей и нянь.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.manyanya03.ru/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
